import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#fbddc7",
        "on-tertiary-container": "#7a97ba",
        primary: "#001836",
        "surface-container-low": "#fff1e9",
        "on-tertiary-fixed-variant": "#2b4968",
        "on-primary": "#ffffff",
        background: "#fff8f5",
        "primary-fixed-dim": "#a9c8fd",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#274774",
        "outline-variant": "#c3c6d0",
        "on-error": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "surface-variant": "#fbddc7",
        "surface-container": "#ffeadc",
        "inverse-primary": "#a9c8fd",
        "tertiary-fixed": "#d1e4ff",
        secondary: "#895100",
        "on-background": "#28180b",
        surface: "#fff8f5",
        "primary-container": "#042d59",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#6e4000",
        tertiary: "#001a31",
        outline: "#747780",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001d35",
        "on-secondary-fixed": "#2c1700",
        "inverse-on-surface": "#ffede3",
        "tertiary-container": "#0d2f4d",
        "surface-tint": "#405f8e",
        "secondary-fixed-dim": "#ffb86c",
        "surface-dim": "#f3d4bf",
        "on-primary-container": "#7796c8",
        error: "#ba1a1a",
        "surface-container-high": "#ffe3d0",
        "inverse-surface": "#3f2d1e",
        "on-secondary-fixed-variant": "#683d00",
        "surface-bright": "#fff8f5",
        "secondary-fixed": "#ffdcbc",
        "on-secondary": "#ffffff",
        "on-surface": "#28180b",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001b3c",
        "secondary-container": "#fea945",
        "on-surface-variant": "#43474f",
        "tertiary-fixed-dim": "#acc9ee",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1200px",
        "section-padding-desktop": "80px",
        "section-padding-mobile": "40px",
        unit: "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Libre Caslon Text", "serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "headline-lg": ["Libre Caslon Text", "serif"],
        "body-md": ["Work Sans", "sans-serif"],
        display: ["Libre Caslon Text", "serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "body-lg": ["Work Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "label-sm": [
          "13px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        display: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
